remake my tic-tac-toe game from the scratch using TDD approach
zinagithub/my-tic-tac-toe pull request #3
Opened 2019-04-12 08:41 UTC by zinagithub

2019-04-17 22:07 UTC, heyapricot requested changes
# We need a bit of order to improve readability/performance
Hello!  I commented the code while trying to follow the flow of the game. There many improvements you can do following the comments I've made. If you need further clarification feel free to schedule a 1 on 1 meeting with me. I'll check the specs in an additional review. Thanks!

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
>  	attr_accessor :matrix, :winCombin, :dim
`attr_accessor` defines an `instance variable` that can be read or write from outside (I can do things like:
```
# main.rb
board = Board.new
dim = board.dim
board.dim = "Let's make this thing explode"
```

Be very careful about deciding which variables should be exposed to external objects.

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
>  	attr_accessor :matrix, :winCombin, :dim
Following the previous comment:
- Why is `dim` an instance variable? Do you plan on using it among different methods?
- Should `dim, matrix, winCombin` be open for `read` and `write` from the outside?

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
> +        Array.new(1){|l| Array.new(dim){|i|  i*(dim-1) + (dim-1)}}
This is hard to read (at least for me). To improve readability / make it easier to understand, can we save each mapping into a method?
```
def initialize
    # ...
    @winCombin = generate_row_combination + generate_column_combination + generate_diagonal_combination
    # ...
end

def generate_row_combination
    Array.new(dim ){|l| Array.new(dim){|i| dim * l + i }}
end
```

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
> +          return false
Suggestion:
```
def change_mat(index_symbol)
    return false unless @matrix[index].nil?
    @matrix[index] = symbol
end
```

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
>     def check_winner(symbol)
What about using [`any?`](https://ruby-doc.org/core-2.6.2/Enumerable.html#method-i-any-3F) instead of `each` and a conditional?

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
> - # board = Board.new(5)
For the `draw?` method this looks prettier: ` @matrix.none?(&:nil?)`
(Let me know if you have questions)

2019-04-17 22:07 UTC, heyapricot commented on lib/board.rb
> - # board = Board.new(5)
For `print_board` try using [`each_slice`](https://ruby-doc.org/core-2.6.2/Enumerable.html#method-i-each_slice) and string interpolation to achieve the same result

2019-04-17 22:07 UTC, heyapricot commented on lib/views.rb
> +def score(player1,player2,score_p1,score_p2)
This is misleading. Do you need a player object or just the player's name?

2019-04-17 22:07 UTC, heyapricot commented on lib/views.rb
> +def new_game(g)
Use meaningful names for your variables, not just characters like `g`

2019-04-17 22:07 UTC, heyapricot commented on lib/views.rb
> +    t = g.turn == "x" ? "1" : "2"
There should be a better handle of the turns. What about counting them? Then you can determine whose turn is it based on the turn number. 
Where should these logic reside?

2019-04-17 22:07 UTC, heyapricot commented on lib/views.rb
> +end
This block does a lot of things. Split in multiple methods. For example, one method that prompts the user for a number between 0 and 9 and returns the user input. 

Some of these methods should reside that will take care of the game flow.

2019-04-23 15:11 UTC, heyapricot requested changes
# About specs
Your first priority should be testing your public methods. Test following the pattern of "I give this input and expect this output". Feel free to reach out for further clarification

2019-04-23 15:11 UTC, heyapricot commented on spec/board_spec.rb
> +
First of all, use [let to share variables with different test cases](http://www.betterspecs.org/#let)

2019-04-23 15:11 UTC, heyapricot commented on spec/board_spec.rb
> +	end
What's the point of testing the initialization?

2019-04-23 15:11 UTC, heyapricot commented on spec/board_spec.rb
> +	describe "check_winner(symbol)" do
For these it'd be great to test all combinations (Rows, columns, diagonals). You can either write a script that does all the writings or pass the board directly. The script would be more 'realistic'

2019-04-23 15:11 UTC, heyapricot commented on spec/game_spec.rb
> +	describe "switch_turn" do
Are you using the turn variable for something? If not, what's the point of testing it?

2019-04-23 20:56 UTC, closed without merging

2019-04-23 20:57 UTC, zinagithub commented
Thanks very much for this code review